const products = [
  {
    id: 1,
    description: "Г/Ц Блинчики с мясом вес, Россия...",
    price: 44.5,
    skidka: 50.5,
    rating: 2,
    discount: 2,
    image: "images/rasm1.png",
  },
  {
    id: 2,
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: 49.39,
    skidka: 30,
    rating: 3,
    image: "images/rasm2.png",
  },
  {
    id:3,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 4,
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: 44.5,
    skidka: 20,
    rating: 4.5,
    discount: 4,
    image: "images/rasm4.png",
  },
  {
    id: 5,
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 599.99,
    skidka: 30,
    rating: 5,
    discount: 2,
    image: "images/rasm5.png",
  },
  {
    id: 6,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm6.png",
  },
  {
    id: 7,
    description: "приятный, ароматный напиток, который заставляет вас ",
    price: 70.2,
    skidka: 30,
    rating: 4,
    discount: 4,
    image: "images/rasm2.png",
  },
  {
    id: 8,
    description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
    price: 49.7,
    skidka: 50,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 1,
    description: "Г/Ц Блинчики с мясом вес, Россия...",
    price: 44.5,
    skidka: 50.5,
    rating: 2,
    discount: 2,
    image: "images/rasm1.png",
  },
  {
    id: 2,
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: 49.39,
    skidka: 30,
    rating: 3,
    image: "images/rasm2.png",
  },
  {
    id: 3,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 4,
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: 44.5,
    skidka: 20,
    rating: 4.5,
    discount: 4,
    image: "images/rasm4.png",
  },
  {
    id: 5,
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 599.99,
    skidka: 30,
    rating: 5,
    discount: 2,
    image: "images/rasm5.png",
  },
  {
    id: 6,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm6.png",
  },
  {
    id: 7,
    description: "приятный, ароматный напиток, который заставляет вас ",
    price: 70.2,
    skidka: 30,
    rating: 4,
    discount: 4,
    image: "images/rasm2.png",
  },
  {
    id: 8,
    description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
    price: 49.7,
    skidka: 50,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 1,
    description: "Г/Ц Блинчики с мясом вес, Россия...",
    price: 44.5,
    skidka: 50.5,
    rating: 2,
    discount: 2,
    image: "images/rasm1.png",
  },
  {
    id: 2,
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: 49.39,
    skidka: 30,
    rating: 3,
    image: "images/rasm2.png",
  },
  {
    id: 3,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 4,
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: 44.5,
    skidka: 20,
    rating: 4.5,
    discount: 4,
    image: "images/rasm4.png",
  },
  {
    id: 5,
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 599.99,
    skidka: 30,
    rating: 5,
    discount: 2,
    image: "images/rasm5.png",
  },
  {
    id: 6,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm6.png",
  },
  {
    id: 7,
    description: "приятный, ароматный напиток, который заставляет вас ",
    price: 70.2,
    skidka: 30,
    rating: 4,
    discount: 4,
    image: "images/rasm2.png",
  },
  {
    id: 8,
    description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
    price: 49.7,
    skidka: 50,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 1,
    description: "Г/Ц Блинчики с мясом вес, Россия...",
    price: 44.5,
    skidka: 50.5,
    rating: 2,
    discount: 2,
    image: "images/rasm1.png",
  },
  {
    id: 2,
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: 49.39,
    skidka: 30,
    rating: 3,
    image: "images/rasm2.png",
  },
  {
    id: 3,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },
  {
    id: 4,
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: 44.5,
    skidka: 20,
    rating: 4.5,
    discount: 4,
    image: "images/rasm4.png",
  },
  {
    id: 5,
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 599.99,
    skidka: 30,
    rating: 5,
    discount: 2,
    image: "images/rasm5.png",
  },
  {
    id: 6,
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 44.5,
    skidka: 10,
    rating: 5,
    discount: 4,
    image: "images/rasm6.png",
  },
  {
    id: 7,
    description: "приятный, ароматный напиток, который заставляет вас ",
    price: 70.2,
    skidka: 30,
    rating: 4,
    discount: 4,
    image: "images/rasm2.png",
  },
  {
    id: 8,
    description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
    price: 49.7,
    skidka: 50,
    rating: 5,
    discount: 4,
    image: "images/rasm3.png",
  },  
 
];